SystemOrganization addCategory: #'Spy2-Tests'!
SystemOrganization addCategory: 'Spy2-Tests-Core'!
SystemOrganization addCategory: 'Spy2-Tests-Plugins'!
SystemOrganization addCategory: 'Spy2-Tests-Plugins-Stubs'!
SystemOrganization addCategory: 'Spy2-Tests-Sender-Stub'!
SystemOrganization addCategory: 'Spy2-Tests-Stub'!
SystemOrganization addCategory: 'Spy2-Tests-Utility'!
SystemOrganization addCategory: 'Spy2-Tests-Utility-Tests'!
